version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: calc_db
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distributedcalc
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calc_backend
    networks:
      - app-network
    environment:
      DB_HOST: db
      GRPC_HOST:
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8000:8000"
    command: ["/app/server"]

  agent:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: calc_agent
    networks:
      - app-network
    environment:
      CONN_HOST: backend
    depends_on:
      - backend
    command: ["/app/agent"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: calc_frontend
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:

networks:
  app-network:
    driver: bridge