POST http://localhost:8080/api/edit_op_duration HTTP/1.1
Authorization: Border eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTM4MTU2NTQsImlhdCI6MTcxMzgxMzg1NCwibmJmIjoxNzEzODEzODU0LCJ1c2VySUQiOjF9.26A6yEFLDvmz2ZH14d3S7P4EyHqyBJmbjIqx7DKRIvU
content-type: application/json
# Boeder <jwt token (login response)>

{
    "operator": "+",
    "delay": 5
}