POST http://localhost:8080/api/expression HTTP/1.1
Authorization: Border eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQwMDY3NjAsImlhdCI6MTcxMzg5ODc2MCwibmJmIjoxNzEzODk4NzYwLCJ1c2VySUQiOjF9.DyG72OoVnXbDe-2tjbF2id-meBKbxL4rPxgYwcS91UM
content-type: application/json
# Boeder <jwt token (login response)>

{
    "exit_id": "2.1",
    "expression": "(1+1)*(1+1)+(1+1)*(1+1)+(1+1)*(1+1)"
}