POST http://localhost:8080/api/expression HTTP/1.1
Authorization: Border eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTM4MDM4NDgsImlhdCI6MTcxMzgwMjA0OCwibmJmIjoxNzEzODAyMDQ4LCJ1c2VySUQiOjF9.i7HzgAfyNRFXFBnKDoVZz3JQCUxpInb6g0H9ZRIzr_o
content-type: application/json
# Boeder <jwt token (login response)>

{
    "exit_id": "1.1",
    "expression": "(2+1+3)/(1-1)"
}